repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        # TODO: might be able to remove redundant args: https://github.com/prettier/pre-commit/issues/22
        args: [--write, --list-different, --ignore-unknown, --single-quote=true]
