repos:
  - repo: https://github.com/prettier/pre-commit
    rev: 57f39166b5a5a504d6808b87ab98d41ebf095b46
    hooks:
      - id: prettier
        # TODO: might be able to remove redundant args: https://github.com/prettier/pre-commit/issues/22
        args: [--write, --list-different, --ignore-unknown, --single-quote=true]
